name: Build Advanced Installer
on: [workflow_dispatch]
jobs:
   advinst-aip-build:
      runs-on: windows-latest
      name: Build Advanced Installer
      steps:
         - name: Check out main repo
           uses: actions/checkout@v4
         - name: Checkout tools repo
           uses: actions/checkout@v4
           with:
              repository: o-adv/bin-21.3.0.0
              path: adv
